export const ACTIONS = {
  TOGGLE_DRAWER: 'SET_DRAWER',
  SET_SELECTED_PLAYERS: 'SET_SELECTED_PLAYERS',
  REMOVE_SELECTED_PLAYER: 'REMOVE_SELECTED_PLAYER',
};

export const MUTATIONS = {
  SET_DRAWER: 'SET_DRAWER',
  SET_SELECTED_PLAYERS: 'SET_SELECTED_PLAYERS',
  REMOVE_SELECTED_PLAYER: 'REMOVE_SELECTED_PLAYER',
};

export const GETTERS = {

};
