export const ACTIONS = {
  TOGGLE_DRAWER: 'SET_DRAWER',
  SET_SELECTED_PLAYERS: 'SET_SELECTED_PLAYERS',
  REMOVE_SELECTED_PLAYER: 'REMOVE_SELECTED_PLAYER',
  GET_PLAYER_PROFILE: 'GET_PLAYER_PROFILE',
  SET_IS_LOADING: 'SET_IS_LOADING',
};

export const MUTATIONS = {
  SET_DRAWER: 'SET_DRAWER',
  SET_SELECTED_PLAYERS: 'SET_SELECTED_PLAYERS',
  REMOVE_SELECTED_PLAYER: 'REMOVE_SELECTED_PLAYER',
  SET_IS_LOADING: 'SET_IS_LOADING',
};

export const GETTERS = {
  GET_COMMON_MATCHES: 'GET_COMMON_MATCHES',
  GET_MAP_STATS: 'GET_MAP_STATS',
};
